import Head from 'next/head'
import Image from 'next/image'
import { enablePromo } from "../utils/launchDarkly"
import styles from '../styles/Home.module.css'

export default function Home({ promoIsEnable}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Shop Online!</a>
        </h1>

        <h2 className={styles.description}>
          Buy anything you want - FREE Shipping on any order within 24 hours 🚀
        </h2>
        {promoIsEnable && <h3>👉 Today only - 50% on all websites with code : PROMO50 🔥</h3>}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const promoIsEnable = await enablePromo()

  return {
    props: {
      promoIsEnable,
    },
    revalidate: 24 * 60 * 60,
  }
}
